import Head from "next/head";
import { ChakraProvider } from "@chakra-ui/react";

function MyApp({ Component, pageProps }) {
	return (
		<>
			<Head>
				<title>Terra Finder Clone</title>
				<meta
					name='description'
					content='Generated by create next app'
				/>
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<ChakraProvider>
				{/* eslint-disable react/jsx-props-no-spreading */}
				<Component {...pageProps} />
			</ChakraProvider>
		</>
	);
}

export default MyApp;
