import Head from "next/head";
import Image from "next/image";
import axios from "axios";
import { useState } from "react";
import fetch from "isomorphic-fetch";
import { MsgSend, MnemonicKey, Coins, LCDClient } from "@terra-money/terra.js";
import { Input, Link } from "@chakra-ui/react";

import API_KEY from "../data/API_KEY";

import styles from "../styles/Home.module.css";
import Account from "./account";

import Landing from "./landing";

export default function Home() {
	const lcd = new LCDClient({
		URL: "https://lcd.terra.dev",
		chainID: "columbus-5",
		gasAdjustment: "1.5",
		gas: 10000000,
	});
	const address = "terra1j5tyxu0d7tejjqe9u9d5vvme4ngqucwlgdx4v0";
	const getBalance = async () => {
		const [balance] = await lcd.bank.balance(address);
	};
	// https://finder.terra.money/mainnet/tx/EE5E2D88FBA128C28D73BA2C5F47D1F16DC93239499958032677C1634DC6F7BD
	// https://finder.terra.money/mainnet/address/terra1sx0vcv48vdqkfd9w9ehxdulmjxthgmweml7jhd
	getBalance();

	let [tx, setTx] = useState();

	return (
		<div className={styles.container}>
			<Head>
				<title>Create Next App</title>
				<meta
					name='description'
					content='Generated by create next app'
				/>
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<Landing />

		</div>
	);
}
